### ISSUE TITLE
Unknown plugin 'add-module-exports'

### ISSUE THREAD

**Issue by francisngo** [ShinyChang/React-Text-Truncate#39] opened 2017-01-17 22:48 UTC
Hello, I am getting an error when trying to use this. 

```
ERROR in ./~/react-text-truncate/lib/index.js
Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "/Users/rr239696/Projects/Personal/parkflix/node_modules/react-text-truncate/.babelrc" at 0, attempted to resolve relative to "/Users/
rr239696/Projects/Personal/parkflix/node_modules/react-text-truncate"
    at /Users/rr239696/Projects/Personal/parkflix/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/rr239696/Projects/Personal/parkflix/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/Users/rr239696/Projects/Personal/parkflix/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/Users/rr239696/Projects/Personal/parkflix/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/Users/rr239696/Projects/Personal/parkflix/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/rr239696/Projects/Personal/parkflix/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/rr239696/Projects/Personal/parkflix/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/rr239696/Projects/Personal/parkflix/node_modules/babel-loader/lib/index.js:38:20)
    at Object.module.exports (/Users/rr239696/Projects/Personal/parkflix/node_modules/babel-loader/lib/index.js:133:12)
 @ ./app/components/ParkCard.jsx 8:19-49
```

**Comment by maxceem** [comment] 2017-01-21 08:39
I have the same.

**Comment by ShinyChang** [comment] 2017-02-17 01:55
Hi @maxceem and @francisngo ,

Sorry for late reply. I will remove it from dependency in next version.

**Comment by ShinyChang** [comment] 2017-06-11 15:37
Sorry, I can not reproduced this issue anymore :(

I tested Node v6 and v8. I have global installed webpack v1 and babel v6. 

Can you give me more environment details? Then I can fix this issue.

**Comment by ShinyChang** [comment] 2017-06-15 04:20
I closed this issue because there is no new reply.

**Closed by ShinyChang** 2017-06-15 04:20 UTC
Labels: bug
